version: '3'
services:
  app:
    container_name: next_afiliados
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./afiliados:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
