version: '3'
services:
  app:
    container_name: next_afiliados
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./afiliados:/app
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
